version: '2'

services:

  postgresql:
    image: bitnami/postgresql:12.5.0
    env_file:
      - .env
    volumes:
      - ./data:/bitnami/postgresql
    networks:
      - airflow

  redis:
    image: bitnami/redis:5.0.10
    env_file:
      - .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data:/bitnami
    networks:
      - airflow

  airflow-worker:
    image: bitnami/airflow-worker:2.0.0
    env_file:
      - .env
    volumes:
      - ./data:/bitnami
#      - "/opt/etl:/external/:rw"
#      - "/home/cdssa/services/public_data/contraloria/declaraciones:/external/cgr/pdfs:rw"
    networks:
      - airflow

  airflow-scheduler:
    image: bitnami/airflow-scheduler:2.0.0
    env_file:
      - .env
    volumes:
      - ./data:/bitnami
#      - "/opt/etl:/external/:rw"
#      - "/home/cdssa/services/public_data/contraloria/declaraciones:/external/cgr/pdfs:rw"
    networks:
      - airflow

  airflow:
    build: ../../scripts/python/airflow/
    #image: docker.pkg.github.com/instidea/controlciudadano/dags:latest
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - ./data:/bitnami
#      - "/opt/etl:/external/:rw"
#      - "/home/cdssa/services/public_data/contraloria/declaraciones:/external/cgr/pdfs:rw"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airlfow.rule=Host(`airflow.controlciudadanopy.org`)"
      - "traefik.http.routers.airlfow.entrypoints=websecure"
      - "traefik.http.routers.airlfow.tls.certresolver=leresolver"
      - "traefik.http.services.airlfow.loadbalancer.server.port=8080"
    networks:
      - airflow
      #- proxy


networks:
  airflow:
  #proxy:
    #external: true
